version: "3.9"
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    networks:
      - hisx2_net
    volumes:
      - jenkins-data:/var/jenkins_home
  
  sonarqube:
    image: sonarqube:latest
    depends_on:
      - db
      - jenkins
    ports:
      - "9000:9000"
    networks:
      - hisx2_net
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_temp:/opt/sonarqube/temp
    
  db:
    image: postgres:latest
    networks:
      - hisx2_net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgreql
      - postgresql_data:/var/lib/postgresql/data

networks:
  hisx2_net:

volumes:
  jenkins-data:

  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_temp:

  postgresql:
  postgresql_data: